language: node_js
node_js:
  - '0.10'
env:
  global:
  - secure:  "UzsWrA+EHUK8Wz2A8O2xx6uFC9oiXy2JeJgCvcT4QxO5oksKbpb+dz0i9V80R9UAUxV6DGTlvnZro7zVgAJfrIQR6pLRKw6LsSyFZe9m6wEGRSASt1Rel5Wlhcf3sIREBE7eR8n6JQpkojjQRCXI7BU0MEyGY14OVXsLBhnTl/M="
  - SITE_NAME="www-thomasvjames-com"
  - AWS_ACCESS_KEY_ID="AKIAI3QW66MMCFEZJFQQ"
  - AWS_DEFAULT_REGION="us-east-1"
  - TOPIC_ARN="arn:aws:sns:us-east-1:503767125918:www-thomasvjames-com-deployment-BuildReadyNotifications-170C5JGRC638S"
before_install:
  - sudo pip install awscli
script:
  - docpad generate --env static
  - mkdir publish
  - tar -czvf publish/$SITE_NAME-$TRAVIS_BUILD_NUMBER.tar.gz -C out .
  - ls -la publish
deploy:
  provider: s3
  access_key_id: AKIAI3QW66MMCFEZJFQQ
  secret_access_key:
    secure: a4dAwKW46ixbq0zwiU0n6FphbHc3AWX/u+ChiWsONnJn7mLvoJ7+zwEQSjvJ24dkh/7euH4vYYgN0/8ps2y8RPisLc0zRjSV6jIJrybTMwCUpJfAXRZut7hu9MlrFcwJGyEshr0eII5kakZ7olDHUEO0umYMp9VcBNfwmHG/aFw=
  bucket: www-thomasvjames-com-deployment-buildartefacts-171heuhj3uzmu
  skip_cleanup: true
  local-dir: publish
  on:
    branch: master
after_deploy:
  - aws sns publish --topic-arn "$TOPIC_ARN" --message "$SITE_NAME-$TRAVIS_BUILD_NUMBER.tar.gz"
