[build]
  publish = "public"
  command = "hugo --gc --minify --enableGitInfo"

[build.environment]
  HUGO_VERSION = "0.55.4"

[context.deploy-preview]
  command = "hugo --gc --minify --enableGitInfo --baseURL $DEPLOY_URL"

[context.branch-deploy]
  command = "hugo --gc --minify --enableGitInfo --buildDrafts --buildFuture --baseURL $DEPLOY_URL"
